CREATE TABLE "f3-siteq-backblast_face_encodings" (
	"id" serial PRIMARY KEY NOT NULL,
	"person_id" integer,
	"aws_face_id" varchar(255) NOT NULL,
	"confidence" real,
	"image_url" varchar(500),
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "f3-siteq-backblast_face_encodings_aws_face_id_unique" UNIQUE("aws_face_id")
);
--> statement-breakpoint
CREATE TABLE "f3-siteq-backblast_people" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "f3-siteq-backblast_photo_faces" (
	"id" serial PRIMARY KEY NOT NULL,
	"photo_id" integer,
	"person_id" integer,
	"aws_face_id" varchar(255),
	"confidence" real,
	"bounding_box" jsonb,
	"is_confirmed" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "f3-siteq-backblast_photos" (
	"id" serial PRIMARY KEY NOT NULL,
	"filename" varchar(255) NOT NULL,
	"s3_key" varchar(500) NOT NULL,
	"upload_date" timestamp DEFAULT now(),
	"processing_status" varchar(50) DEFAULT 'pending',
	"face_count" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE "f3-siteq-backblast_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "f3-siteq-backblast_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "f3-siteq-backblast_users" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp,
	"image" varchar(255),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "f3-siteq-backblast_face_encodings" ADD CONSTRAINT "f3-siteq-backblast_face_encodings_person_id_f3-siteq-backblast_people_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."f3-siteq-backblast_people"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "f3-siteq-backblast_photo_faces" ADD CONSTRAINT "f3-siteq-backblast_photo_faces_photo_id_f3-siteq-backblast_photos_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."f3-siteq-backblast_photos"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "f3-siteq-backblast_photo_faces" ADD CONSTRAINT "f3-siteq-backblast_photo_faces_person_id_f3-siteq-backblast_people_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."f3-siteq-backblast_people"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "f3-siteq-backblast_post" USING btree ("name");